restforce/restforce

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
The use of `Hash#delete` in `Restforce::Concerns::API#update!` and `Restforce::Concerns::API#upsert!` means that the `attrs` passed into the Restforce client are mutated. It's generally not desirable for an external dependency like this gem to modify provided data in-memory.
This updates those methods to pull out the desired ID to update or upsert in a non-destructive way.
> Stop Restforce::Concerns::API#update! and Restforce::Concerns::API#upsert! mutating provided attributes

- README.md
I had an issue trying to use Restforce with Sidekiq in a rails application. Turns out that reusing the client object causes a whole bunch of strange issues to manifest. I'm not positive if Restforce stores some state on the client or if it's an issue with Net::HTTP but I figured a note in the README would be nice to possibly help out other devs.
> Add a note about client object thread safety to the README

- lib/restforce.rb
- spec/unit/config_spec.rb
`Restforce.new` was dropping block arguments when calling through to the
underlying `Data::Client`.
> Allow blocks to pass through

- lib/restforce/collection.rb
- spec/unit/collection_spec.rb
I have a Salesforce query that returns many results using the lazy-fetched enumerable Restforce::Collection. Something like
```ruby
results = restforce_client.query("Select Id from #{sf_class}")
results.each_slice(1_000) do |slice| 
delay_send_spam_email(slice)
end
```
Using each_slice with the SF page size seems very clean, and efficient, since I can fetch a single page of results, and only get the next page when I'm ready to process it.
But sometimes SF returns pages of 1k results, sometimes 2k, and I don't want to have to figure that out.
So I'd like to do 
```ruby
results.each_slice(results.page_size) do |slice| 
#...
```
> add a page_size method to Restforce::Collection

- .travis.yml
See https://www.ruby-lang.org/en/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/
for more details.
Alternative to https://github.com/ejholmes/restforce/pull/163.
> Test against latest Ruby teeny versions

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
New mergeable version of #150, with slightly improved specs and formatting.
> Add #recent method to the client, reimplementing #150

- README.md
- lib/restforce/config.rb
- spec/unit/config_spec.rb
Probably not a good idea to use such a generic environment variable, and doesn't follow the pattern in the rest of the gem.
This will go out as part of 2.1.0.
> Change proxy environment variable from PROXY_URI to SALESFORCE_PROXY_URI

- lib/restforce/middleware/authentication.rb
- spec/unit/middleware/authentication/password_spec.rb
- spec/unit/middleware/authentication/token_spec.rb
- spec/unit/middleware/authentication_spec.rb
There is another Faraday connection created in the authentication middleware, and this connection didn’t respect the adapter option, which meant that Net::HTTP was always used for that connection.
> Respect Faraday adapter option in authentication

- README.md
The existing documentation for Restforce's Streaming support
did not mention the version of the `faye` gem to be used.
This is a small change to the documentation to indicate that
version `0.8.9` is that known working version of faye.
Resolves https://github.com/ejholmes/restforce/issues/194
> Update Restforce Streaming Documentation to indicate `faye` version

- lib/restforce/middleware/caching.rb
- spec/integration/abstract_client_spec.rb
- spec/support/mock_cache.rb
Faraday middleware has been updated and uses #read instead of #fetch.
MockCache has been updated to implement #read. #fetch remains in case we
want to support an older version of faraday_middleware.
See faraday_middleware commit:
https://github.com/lostisland/faraday_middleware/commit/3f559c18ee82701d8a1d04faf2bfd92d180b737b#diff-32d8ad0f070291407b5ceb8e788fb40fR47
Current failing travis build: https://travis-ci.org/ejholmes/restforce/jobs/81812544
> Fix caching spec

- lib/restforce/concerns/connection.rb
- lib/restforce/middleware/caching.rb
- lib/restforce/middleware/raise_error.rb
- spec/integration/abstract_client_spec.rb
- spec/support/mock_cache.rb
- spec/unit/middleware/raise_error_spec.rb
This fixes #208. This branch is on top of `kouno:fix-cache-read` to see all tests pass.
> Fix raise error parsing

- lib/restforce/middleware/raise_error.rb
When using ActiveSupport, the String class actually defines #first and
this would cause the body to be truncated to the first character.
The current tests are valid and still pass with this fix, but the
failing behavior only shows if you have active support included in your
project.
@timrogers sorry about that one. :see_no_evil:
> Check for type instead of using duck typing

- lib/restforce.rb
- lib/restforce/middleware/authentication.rb
Introduces a new error class, `ServerError`, which is raised when authentication fails with a 5xx code.
> Raise a server error when authentication fails

- lib/restforce/concerns/api.rb
- lib/restforce/middleware/raise_error.rb
- spec/unit/middleware/raise_error_spec.rb
If you try to insert or update (upsert) a record using an external ID (see <https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm>) and the external ID provided is not unique, Salesforce returns a 300 response with a list of matching records as an array. This 300 behaviour can also be expected elsewhere in the API (<https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/errorcodes.htm>).
This allows us to handle that response and raise an exception, as you'd expect, and provides access to the list of matching IDs returned, since once can access the response body of a `Faraday::ClientError` with `#response` (<http://www.rubydoc.info/github/lostisland/faraday/Faraday/ClientError>).
Fixes #224.
> Handle 300 errors triggered by an upsert where the external ID matches multiple records

- lib/restforce/middleware/raise_error.rb
- spec/unit/middleware/raise_error_spec.rb
For consistency with the 300 and 400-600 `Faraday::Error::ClientError`s we raise in `Restforce::Middleware::RaiseError`, an HTTP 413 response should raise an error with a message in the same format ("#{http_status_code}: #{description_of_error}").
This is potentially a non-backwards-compatible change, in the unlikely event that people are doing some kind of special rescuing of this error.
> Improve the consistency of `Faraday::Error::ClientError`s raised by the `RaiseError` middleware

- README.md
- lib/restforce/concerns/api.rb
- spec/fixtures/sobject/get_deleted_success_response.json
- spec/integration/abstract_client_spec.rb
- spec/unit/concerns/api_spec.rb
Followed the pattern for `get_updated` and took the sample response from the [Salesforce developer docs](https://developer.salesforce.com/docs/atlas.en-us.202.0.api_rest.meta/api_rest/dome_get_deleted.htm)
> Add support for get_deleted

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
When I pass strings contains multibytes characters as external ID to Restforce::Concerns::API#upsert!, it raise `URI::InvalidURIError:URI must be ascii only` exception.
To get rid the failure, URI encode the external ID when embeded it into request path.
> encode external id for upsert! to get rid of error with multibytes external id

- Gemfile.travis
Travis has been failing because it was attempting to install a new version of Rack (a dependency of Faye) which only supports late Ruby versions. This fixes the problem by specifying an earlier working version of Rack.
> Fix Travis CI by specifying a version of Rack

- .travis.yml
We're not running tests on Ruby 2.3 which is a bit sad, so let's start doing that.
> Test on Ruby 2.3.1

- lib/restforce/config.rb
- spec/unit/config_spec.rb
All other options have a related ENV var from the system that's hosting this gem.  api_version defaults to 26.0 but there's no way to set this from an ENV var upon deployment.  This change will allow the variable to be set or it will default to v26.0 if none was specified.
> set SF api version from env var

- CHANGELOG.md
- README.md
- lib/restforce.rb
- lib/restforce/document.rb
- lib/restforce/mash.rb
- spec/unit/document_spec.rb
- spec/unit/mash_spec.rb
Noticed documents were not supported.  Attachments and Documents are similar enough and both contain 'Body' attributes that host the file information.  This was essentially a copy and replace with the Attachment class.
> Add Salesforce Document support

- README.md
From [databasedotcom readme](https://github.com/heroku/databasedotcom): "DEPRECATED: Please use restforce instead."
> databasedotcom deprecated. remove from readme

- README.md
As per requested in https://github.com/ejholmes/restforce/issues/268, add an example that shows how the Tooling API can be used.
The example creates a "Twitter Username" field on the standard "Account" object.
> Add a Tooling API example to the README

- .travis.yml
- lib/restforce/version.rb
- restforce.gemspec
This is a PR with no changes to show off that master doesn't build due to something changing in the gem dependencies. 
/cc https://github.com/ejholmes/restforce/pull/273
> Deprecate ruby 1.9.x support

- Gemfile.travis
- lib/restforce/concerns/caching.rb
- lib/restforce/middleware/caching.rb
- lib/restforce/version.rb
While instrumenting our code with zipkin we noticed the auth headers being included in cache keys. While hashing them isn't perfect it's better than what we're doing now.
> No credentials in cache keys

- README.md
- lib/restforce/concerns/base.rb
- lib/restforce/concerns/connection.rb
- lib/restforce/middleware.rb
- lib/restforce/middleware/custom_headers.rb
- spec/support/client_integration.rb
- spec/unit/middleware/custom_headers_spec.rb
The Restforce gem does not currently support custom HTTP request headers out of the box.  It's currently possible for users to define their own middleware in their application to handle request header injection (discussion here: https://github.com/ejholmes/restforce/issues/109).  While this works, there is logic in Salesforce API interactions that can be triggered based on the presence of custom headers, so it is justifiable to support this in Restforce.
Added `Restforce::Middleware::CustomHeaders` to the gem.  This allows user to pass a hash of custom headers values into the client when initializing.  If a valid hash is provided, the values in the hash are injected into the headers of every HTTP request made by that specific client instance.
Here's an example (I added this to the README …
> Custom Header middleware

- .travis.yml
* Switches from `ruby-2.4.0-preview2` to the final version
* Update Rubygems and Bundler to the latest version before running the build (to fix issue when building `rainbow`)
> Fix the build of Ruby 2.4 in Travis

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
Simplify extracting `external_id` from `attrs` hash by using
`Hash#delete` with all possible transformations of `field`. Avoids
iterating through `attrs` twice.
Addresses #263.
> Add support for upsert with Id field

- lib/restforce/mash.rb
When using `hashie >= v3.5.0` any `Client#describe` call currently results in lots of
```
You are setting a key that conflicts with a built-in method Restforce::Mash#length defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```
warnings, bc. of the `fields`-Array as `fields` have a `length` key.
The logging layer of Hashie was introduced in `hashie v3.5.0`. And the `disable_warnings` method was introduced in `hashie v3.5.2`. See https://github.com/intridea/hashie/blob/master/CHANGELOG.md.
Other gems using `hashie` went this way as well, see for example https://github.com/elastic/elasticsearch-rails/issues/666.
> Disable Hashie warnings for re-defined methods such as length

- lib/restforce/concerns/api.rb
- spec/integration/abstract_client_spec.rb
- spec/unit/concerns/api_spec.rb
Discovered as a result of https://github.com/ejholmes/restforce/issues/159 - when the external id was missing after being deleted, the error surfaced as `NoMethodError·undefined method 'gsub' for nil:NilClass` since `upsert!` would try to URI encode `nil` (https://github.com/ejholmes/restforce/blame/master/lib/restforce/concerns/api.rb#L374)
> Raise error in upsert! when external id is missing

- lib/restforce/middleware/authentication.rb
- spec/unit/middleware/authentication_spec.rb
This change ensures that the SSL options passed to the request are also used for the authentication request (if it is needed) in addition to the actual resource request. This allows enforcement of an SSL version (eg. TLS v1.2) for increased security.
See also: #238
> Use SSL options for authentication request

- Gemfile
- Gemfile.travis
The gem is compatible with versions of Faraday up to v1.0 (yet to be released! - currently the latest is v0.12.1) but at present, our tests only work with v0.11.0 and earlier (the current version is v0.12.1, so we're not too far behind).
This updates our `Gemfile`s to lock to this version so tests will pass again in Travis. I'll look as soon as I can at fixing the tests for `Restforce::Concerns::Connection` so they can work with newer Faraday versions - looks like its API has changed.
> Fix Faraday version for development and testing to v0.11.0

- restforce.gemspec
Makes it easy to programatically find the source code and changelog for `restforce`, using the rubygems API. More details on the direction of travel for gemspecs is [here](https://github.com/rubygems/rubygems.org/issues/1127) and [here](https://github.com/rubygems/rubygems.org/pull/1234), and the current state is [here](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb).
> Add gemspec metadata

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
If external Id is a Fixnum extract_case_insensitive_string_or_symbol_key_from_hash will return it as a Fixnum too, and we'll get Undefined method strip for Fixnum. Happens for symbols too.
> Undefined method strip when external_id is a Fixnum

- CHANGELOG.md
- CONTRIBUTING.md
- LICENSE
- README.md
- restforce.gemspec
This PR also:
* Changes the TravisCI badge in the README to a CircleCI badge
* Updates the copyright notice to say 2012 instead of 2017, and include my name
* Fixes the website URL in the .gemspec, which should be HTTPS
> Update references to ejholmes/restforce to restforcegem/restforce

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- restforce.gemspec
We're moving again! @antwonlee has let us use the `restforce`
GitHub organisation name that he previously owned (now
[restforce-demos](https://github.com/restforce-demos)).
> Update links to point to restforce/restforce

- lib/restforce/concerns/connection.rb
Faraday had enabled gzip decompression for httpclient by default since v0.9.2.
#https://github.com/lostisland/faraday/pull/457
Therefore, no need of `Gzip` middleware for decompression.
> drop Gzip middleware for httpclient adapter

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
There is already a slash in the `api_path` method below and the duplicate slashes is causing us to get 404 errors when using `get_updated`. 
https://github.com/restforce/restforce/blob/467be4f6db4db10c64b1ec7fa48cb47de46f548a/lib/restforce/concerns/api.rb#L480
> removes leading slash from `api_get` calls

- lib/restforce/concerns/api.rb
- spec/unit/concerns/api_spec.rb
This fixes a regression introduced in b3a52e8cfcfd for the case when
response body is not a Hash but an empty String.
*Expected behavior*:
it returns `true`
*Current behavior*:
it raises `undefined method 'fetch' for "":String`
Example request/response:
```bash
D, [2018-08-03T11:27:05.718522 #4] DEBUG -- request:
url: "https://obfuscated--test--url.my.salesforce.com/services/oauth2/token"
method: :post
headers: {"User-Agent"=>"Faraday v0.12.2", "Content-Type"=>"application/x-www-form-urlencoded"}
body: "grant_type=password&client_id=..."
D, [2018-08-03T11:27:06.426882 #4] DEBUG -- response:
status: "200"
headers: {"date"=>"Fri, 03 Aug 2018 11:27:06 GMT", "strict-transport-security"=>"max-age=31536002; includeSubDomains", ..., "connection"=>"close"}
body: …
```
> Fix upsert! regression on empty String response body

- lib/restforce/concerns/streaming.rb
- spec/unit/concerns/streaming_spec.rb
Thanks to the existing code in Restforce, I was able to get up and running with the PushTopic streaming API in just a few lines of code. We have used this library on a couple of projects now.
For PushTopics, Salesforce added [the ability to replay messages](https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/using_streaming_api_durability.htm) (see #237). This PR adds an options hash to the `subscribe` method on clients, which allows us to pass a message id to replay from using a client extension. With this code, you can replay messages:
```
client.subscribe push_topic_name, replay: 7 do |message|
end
```
This will replay message 8 and up (based on Salesforce's documentation of this feature.) I have verified the functionality with a local script that points …
> Implement push topic replay

- README.md
Just a simple fix for the main `Readme.md` in the Streaming API section.
> Fix syntax error in Streaming API example

- lib/restforce/concerns/api.rb
- spec/integration/abstract_client_spec.rb
The client used to call CGI.escape on ids present in URLs.
This can lead to unexpected behavior where a space in an id
is encoded as a +, but is not decoded by Salesforce leading
to duplicate objects during upsert.
This commit replaces the CGI.escape calls with
ERG::Util.url_encode calls which encode space as %20.
> Properly URL escape ids with spaces in them

- CHANGELOG.md
- lib/restforce.rb
- lib/restforce/middleware/raise_error.rb
- spec/unit/middleware/raise_error_spec.rb
Currently, Restforce raises `Faraday::Error::ClientError` for nearly every kind of error that can occur. Errors like `INVALID_OPERATION` are problems in client code that require human intervention to fix while errors like `REQUEST_LIMIT_EXCEEDED` or `SERVER_UNAVAILABLE` are transient errors that could be handled programmatically by queuing work and retrying later.
This pull request unwraps the various error responses that a client may receive from Salesforce so that API consumers can more easily differentiate errors.
> Name exceptions for the error codes that might be returned from Salesforce.com

- README.md
- lib/restforce/concerns/streaming.rb
- spec/unit/concerns/streaming_spec.rb
Unfortunately the streaming concern currently hardcodes `/topic/` in the channel name, which limits the number of use-cases it can be used for, especially now that Salesforce have [a number of other ways](https://trineo.com/blog/2019/04/push-vs-cdc) to publish cometD messages.
> Add support for platform events, CDC, generic events, etc

- spec/unit/sobject_spec.rb
When running the test suite, rspec spits out the following warning:
```
`raise_error` was called with non-proc object nil
```
This is happening whenever `raise_error` is used with a non-block subject, because then, the code is executed before the expectation was set up and therefore it may yield unexpected results.
This change wraps the subject in a `lambda` so that the warning goes away and the spec works as expected. I also refactored a related spec, because due to the improved subject set up it may now become a bit simpler.
> Fix rspec warning during test runs

- lib/restforce/mash.rb
- spec/unit/mash_spec.rb
This fixes an issue in mash when the `attributes` key is present but the value is nil. Currently when this happens it fails on line 31: `case (val['attributes']['type'])` with:
```
NoMethodError: undefined method `[]' for nil:NilClass
```
Now when this happens we just return `Restforce::SObject`.
> Fix nil attributes error

- Gemfile
- README.md
- lib/restforce.rb
- lib/restforce/concerns/api.rb
- lib/restforce/file_part.rb
- lib/restforce/upload_io.rb
- restforce.gemspec
- spec/integration/abstract_client_spec.rb
- spec/unit/concerns/connection_spec.rb
- spec/unit/middleware/authentication_spec.rb
I followed: https://github.com/lostisland/faraday/blob/master/UPGRADING.md
I also looked at the differences between older versions (https://github.com/lostisland/faraday/blob/v0.15.4/lib/faraday/error.rb) and the latest version (https://github.com/lostisland/faraday/blob/v1.0.1/lib/faraday/error.rb) to see if there was common behaviour we could exploit. That's where rescuing `Faraday::Error` came from.
Fixes #530
Closes #526
Closes #544
> Add support for faraday 1.x

- .circleci/config.yml
- .rubocop.yml
- restforce.gemspec
This PR drops support for Ruby 2.4, since it has reached end of life, and updates our CircleCI testing matrix so we drop testing against 2.4 and use the latest patch versions of 2.5, 2.6 and 2.7.
This will be released as a major version since it breaks Ruby compatibility, and will require README updates to make that clear.
> Drop support for Ruby 2.4 and update build matrix

- CONTRIBUTING.md
- lib/restforce/collection.rb
- spec/unit/collection_spec.rb
Also fixes a link in CONTRIBUTING.md.
The `empty?` method exists on many Ruby collections like `Array`, `Hash`, and `Set`.  But it isn't part of `Enumerable` presumably because not every iterator knows the full length of the collection, iterating might be destructive, iterating might be expensive, or the enumeration could be infinite.
But `Restforce::Collection` knows the length of the collection without having to make another API request.  So I think it would be nice to have `empty?` to more closely match some of the other Ruby collection interfaces.
> Add empty? to Restforce::Collection

- restforce.gemspec
JSON has been in the stdlib since 1.9, there's no need to declare any dependencies at all. Just `require 'json'`.
Since it is generally a good idea to reduce the number of dependencies this Pull Request aims to remove the superfluous dependency on the `json` gem.
> Remove 'json' gem dependency

- README.md
- lib/restforce/concerns/caching.rb
- lib/restforce/config.rb
- lib/restforce/middleware/caching.rb
- spec/unit/concerns/caching_spec.rb
I would like to take advantage of Restforce's caching feature but would prefer to opt in as I make changes to the code base. This adds the ability to opt in to caching on a per-request basis similar to `.without_caching` method opts out on a per-request basis. 
The changes I made here seemed to require the least amount of systematic alterations. It adds a method and makes a private config public with a default. The one negative I see to this option is that because of the way things are setup in `Restorce::Concerns::Connection`, all requests will actually be cached. Only those within `.with_caching` will not expire the cache first, forcing a fresh request, thus accomplishing my intent.
It seems like if we wanted to only write to the cache in `.with_caching` or likewise not write to the …
> Adds ability to opt in to caching on a per-request basis

- README.md
I spent *way* longer than I'd like to admit trying to figure out why my refresh tokens weren't working correctly. Eventually I discovered they were being sent to the production environment rather than the sandbox one. Re-reading the docs I see that mentioned but since it appeared under the proxy section I'd over looked it.
> Clarify that refresh process uses host option

- lib/restforce.rb
- lib/restforce/error_code.rb
- lib/restforce/middleware/raise_error.rb
- spec/spec_helper.rb
- spec/unit/error_code_spec.rb
- spec/unit/middleware/raise_error_spec.rb
The Salesforce REST API can return a range of `errorCode`s representing different kinds of errors. To make these easy to
handle in your code, we want to turn these into individual, specific exception classes in the `Restforce::ErrorCode` namespace that inherit from `Restforce:: ResponseError`.
Today, this behaviour is achieved by taking the error code returned by Salesforce (e.g. `ALL_OR_NONE_OPERATION_ROLLED_BACK`), normalising it into something that looks like a Ruby class name (e.g. `AllOrNoneOperationRolledBack`) and then looking it up inside the `Restforce::ErrorCode` module using `const_get` to find the correct error class to raise.
`Restforce::ErrorCode` then uses `const_missing` to dynamically define the error class requested - so in short, if Salesforce returns an error, a class …
> Explicitly define error classes for known Salesforce errors

- README.md
This hopefully will address the confusion regarding when the upsert method returns an Id: https://github.com/restforce/restforce/issues/253
> Update README doc for upsert method

- lib/restforce/error_code.rb
This handles the undocumented `API_CURRENTLY_DISABLED`, `MALFORMED_QUERY` and `INVALID_QUERY_FILTER_OPERATOR` errors returned by the Salesforce API, raising error-specific exceptions.
> Handle three unhandled API errors returned by Salesforce

- lib/restforce/error_code.rb
Fixes #567 and #568. Thanks @wkirby!
> Handle `REQUEST_LIMIT_EXCEEDED` and `SERVER_UNAVAILABLE` errors from Salesforce

- lib/restforce/error_code.rb
Fixes #571 reported by @embertel.
> Handle `EXCEEDED_MAX_SEMIJOIN_SUBSELECTS` error returned by Salesforce

- Gemfile
- lib/restforce/upload_io.rb
- restforce.gemspec
> Allow Faraday versions up to, but not including, v1.1 to be used with Restforce 4.x

- lib/restforce/error_code.rb
This handles the undocumented `API_DISABLED_FOR_ORG` error returned by the Salesforce API and raises a `Restforce::ErrorCode::ApiDisabledForOrg` exception.
> Handle the `API_DISABLED_FOR_ORG` error returned by Salesforce

- lib/restforce/error_code.rb
> Handle `INVALID_SIGNUP_COUNTRY` error returned by Salesforce

- restforce.gemspec
> Update gemspec to reflect that `restforce` `v3.x` doesn't work with `faraday` `v1.0.0`

- lib/restforce/error_code.rb
> Handle `MALFORMED_SEARCH` error returned from Salesforce

- lib/restforce/concerns/composite_api.rb
- spec/unit/concerns/composite_api_spec.rb
Changes the capitalization expected in the compositeResponse object to match the docs here:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/responses_composite.htm
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_subrequest_result.htm
I also tested the changes locally both with and without `all_or_none: true` and the `CompositeAPIError` appears to be raised with the last error as expected.
I am unsure if this is an error in the initial implementation, or if there is some API version out there that uses this as is. The composite_api_spec tests are written with API version 38 (which is much older than when composite support was added to restforce, and might just be copy/paste from other specs?). I couldn't find …
> Fix compositeResponse capitalization

- restforce.gemspec
This commit limits the gem to only working with compatible Faraday versions between `0.9.0` and `1.8.x`.
The recently released `1.9.x` series isn't compatible with some magic we have in `lib/restforce/file_part.rb` to maintain compatability with pre-1.0 versions - see https://github.com/lostisland/faraday/pull/1367 for the relevant changes.
> Restrict Restforce to Faraday versions before `v1.9.x`

- lib/restforce/collection.rb
- spec/fixtures/sobject/list_view_results_success_response.json
- spec/unit/collection_spec.rb
Closes https://github.com/restforce/restforce/issues/706.
As described in the issue above, there are some Salesforce REST endpoints that lack a `"totalSize"` property and instead use `"size"`. One such endpoint is [List View Results](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_listviewresults.htm). When attempting to use `.size` or `.present?` (using ActiveSupport), you would get errors since it's trying to access a non-existent property. This provides a fallback by trying to use the `"size"` property if present.
I used the example output from the docs linked above as a test fixture, truncated and edited to only contain one result.
> Get Collection's length via "size" property if "totalSize" does not exist

- lib/restforce/middleware/authentication.rb
This is a duplicate of @nhocki's excellent work in #712 - but rebased on `main` so all of the tests run in GitHub Actions, and with [4f7de99](https://github.com/restforce/restforce/pull/712/commits/4f7de991c9e15d95eb8d4a65939905397589f736) removed, since those Rubocop fixes were already merged elsewhere.
> Follow redirects on authentication

- .github/workflows/faraday.yml
- lib/restforce/file_part.rb
- restforce.gemspec
This PR:
* fixes the gem on Faraday v1.10.x, loading the correct code for multipart support
* adds tests to our CI process to make sure that Faraday v1.10.x works
* tightens up the gemspec so versions of Faraday after v1.10.0 _will not_ be allowed
Our dependency declaration looks like this:
```ruby
gem.add_dependency 'faraday', '<= 1.10.0', '>= 0.9.0'
```
Unsurprisingly, this means that the gem will allow versions of `faraday` between v0.9.0 and v1.10.0 inclusive, i.e.:
* v0.8.0 is _not_ allowed
* v0.9.0 is allowed
* v1.1.1 is allowed
* v1.10.0 is allowed
* v1.9.0 is allowed
* v1.10.1 is _not_ allowed
If Faraday consistently used semantic versioning, then v1.10.1 or v1.11.0 (neither of which exist!) should be safe, but there has been a history of breaking changes between versions (e.g. …
> Make Faraday v1.10.0 the latest supported version

- README.md
- lib/restforce/concerns/api.rb
I thought it would be helpful to indicate in the documentation that when `find` does not find anything, it would  raise an error instead.
> Document on `find` raising error

- lib/restforce/error_code.rb
> Handle `EXCEEDED_ID_LIMIT` error returned by Salesforce

- .github/workflows/faraday.yml
- .github/workflows/faraday_legacy.yml
- lib/restforce/file_part.rb
- spec/support/faraday_version_helpers.rb
- spec/unit/concerns/connection_spec.rb
- spec/unit/middleware/authentication_spec.rb
This PR started with a simple observation: the gemspec says that the gem support Faraday 0.9.0 onwards, but we weren't actually testing against anything against below v1.x in CI.
It ends up making two distinct changes:
* **Test against Faraday v0.x minor versions from v0.9.0 onwards in CI - and get those tests passing**: I enabled testing, and found that a bunch of tests were broken - mostly due to differences in Faraday internals between versions, which our tests can see because we dig quite deep into Faraday to check that the gem actually works as expected.For those cases, I have introduced separate tests for Faraday 0.x and Faraday 1.x onwards. An alternative option would be to remove these Faraday internals tests, but I'd like to be more thoughtful and strategic on that.
* **Fix …
> Fix compatability with Faraday v0.16.x and run tests against all Faraday 0.x minor versions

- .github/workflows/build.yml
- .rubocop.yml
- lib/restforce.rb
- restforce.gemspec
This drops support for Ruby 2.6, which has reached end of life (EOL)
I plan to release this change as a new major version, v6.0.0, starting with a release candidate version to gather feedback, so I am merging into a `v6.0.0.rc.1` branch. In the major version, this will be combined with dropping support for Faraday versions before v1.1.0 (and adding support for Faraday v2.x!) - see #721.
> Drop support for Ruby 2.6, which has reached end of life (EOL)

- README.md
Makes the readme a bit more automatically up to date by not specifying an exact api version.
> Don't specify latest api version in docs

- README.md
This pull request adds a note about the risk of using JWT auth mechanism without any caching. 
We are using restforce in our of our internal applications and we ran into the `LOGIN_RATE_EXCEEDED` error from Salesforce ([reference](https://help.salesforce.com/s/articleView?id=000312767&type=1)) once we exceed 3600 logins per hour. We implemented an internal caching mechanism that reuses bearer tokens to overcome this error. Hopefully the note we are adding will prevent other developers from running into the same issue as us.
> Add a note about JWT token caching to README.md

- .github/workflows/faraday.yml
- restforce.gemspec
This updates the gemspec to allow Faraday versions up to `2.7.0` - effectively adding official support for v2.5.x and v2.6.x. At the same time, it includes these Faraday minor versions in our testing process.
We take this approach to Faraday compatibility because Faraday has an unfortunate history of reasonably frequently releasing minor versions (`major.minor.patch`) with breaking changes, and we want to check that each version actually works.
Inspired by #758.
> Add support for Faraday v2.5.x and v2.6.x

- lib/restforce.rb
- lib/restforce/concerns/composite_api.rb
- spec/unit/concerns/composite_api_spec.rb
Related to https://github.com/restforce/restforce/issues/766
Allow `CompositeAPIError` to include Faraday's response
I added one test related to this change &  ran rspec locally.
> include response body for CompositeAPIError

- .github/workflows/build.yml
- Gemfile
This PR updates our build matrix to run tests against Ruby 3.2.0, the latest version, in CI.
To enable this change, I also update the default version of Faraday in development and testing from v1.8.0 to v2.6.0. 
This is because, due to a [bug](https://github.com/lostisland/faraday/issues/1479) in Faraday, the older v1.x version we're using doesn't work with the latest Ruby. This seems like a sensible change anyway, given that we do always test older Faraday versions.
> Run tests against Ruby v3.2.0 in CI

- spec/unit/concerns/composite_api_spec.rb
This fixes some Composite API-related tests that somehow ended up turning red after #756 was merged. The failures are related to new keyword arguments related behaviour in newer Ruby versions.
> Fix broken Composite API-related tests

- .github/workflows/faraday.yml
I updated the `faraday.yml` file to run tests against the latest mirror versions of Faraday.
> Test against latest minor versions of Faraday

- .gitignore
- lib/restforce/concerns/base.rb
- lib/restforce/concerns/connection.rb
- lib/restforce/config.rb
- spec/unit/config_spec.rb
Passes a new option (clear_authorization_header) through to the FollowRedirects middleware so that the authorization header can be included in requests as we follow redirects across Salesforce domains.
> Add new `clear_authorization_header` option to decide whether to continue sending authentication headers when redirected

- lib/restforce/error_code.rb
> Handle `INSUFFICIENT_ACCESS` error returned by Salesforce

- lib/restforce/error_code.rb
Here are some missing error classes that are returned by Chatter API. Fixes Issue #807 as well as some others.
- Cannot delete owner error: When you attempt to delete an owner of a Chatter group
- Cannot post to archived group error: When you attempt to post to an archived Chatter group
- Invalid input error: When attempting to post with an invalid record id to Chatter
- Invalid markup error: When Chatter feed element segments are invalid (nested unordered lists are past 5 deep)
- Invalid search error: When feed element search contains invalid input to Chatter
> Add missing Chatter API response errors

- lib/restforce/concerns/connection.rb
- lib/restforce/middleware/authentication.rb
- lib/restforce/middleware/json_request.rb
- lib/restforce/middleware/json_response.rb
Since the gem was registering it's own custom JSON middleware as `:json` it could end up taking precedence over the default Faraday JSON middleware in application code and break things.
This PR changes the registration name to `:restforce_json` to avoid any chance of collision.
> Register JSON middleware as restforce_json to avoid overwriting default

- .github/workflows/build.yml
- .rubocop.yml
- README.md
- UPGRADING.md
- lib/restforce/middleware/json_request.rb
- lib/restforce/middleware/raise_error.rb
- restforce.gemspec
In keeping with Restforce's usual practice, this ends supports for Ruby 2.7, which has reached end of life and is no longer supported or kept up to date with security patches.
This change will be released as a new major version, v7.0.0.
> Drop support for Ruby 2.7, which has reached end-of-life

- lib/restforce/concerns/authentication.rb
- lib/restforce/middleware/authentication.rb
- lib/restforce/middleware/authentication/client_credential.rb
- spec/unit/concerns/authentication_spec.rb
- spec/unit/middleware/authentication/client_credential_spec.rb
add support `grant_type=client_credentials`
OAuth 2.0 Client Credentials
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5
> Add support for oauth client credential

- .github/workflows/faraday.yml
- Gemfile
- restforce.gemspec
This adds support for `faraday` v2.8.x, and tests the gem against that Faraday version as part of our CI process. We will also now use v2.8.x by default in development and testing.
> Add support for `faraday` v2.8.x

- lib/restforce/error_code.rb
Thanks to @Rodrigo-Cardoso for the heads up about this error!
Fixes #849.
> Handle `APEX_REST_SERVICES_DISABLED` error returned by Salesforce

- .github/workflows/faraday.yml
- Gemfile
- restforce.gemspec
This PR also updates our CI workflows to test against the latest patch version of `faraday` v2.8.x, v2.8.1.
> Add support for `faraday` v2.9.x, tested in CI

- README.md
- lib/restforce/concerns/composite_api.rb
- spec/unit/concerns/composite_api_spec.rb
Add support for GET request in Composite API library. 
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/requests_composite.htm#subrequest
> Composite API: Add support for GET

- README.md
@rh-taro  -- the README misled me into setting instance_url but that's now how Client Cred flow needs to work -- the authorization request needs to be made against the org's My Domain which means you need to set the `host` option, not `instance_url`
Can you review this README change and then @timrogers can you merge it? 
Thanks!
> Updates README to reflect the need to set `host` option, not `instance_url` when doing Client Credentials flow

- README.md
- spec/unit/config_spec.rb
I'm trying to clarify the order of precedence between environment variables, `Restforce.configure` and `Restforce.new(options)`.
I added a small section at the bottom of the readme and some tests to proof it.
> Add initialization precedence between ENV, config and attributes

- lib/restforce/middleware/gzip.rb
- lib/restforce/patches/parts.rb
- spec/unit/middleware/gzip_spec.rb
> Explicitly require `StringIO` where it's used

- .github/workflows/faraday.yml
- Gemfile
- restforce.gemspec
Hi, I'd like to bump Faraday to 2.10.0. It effectively just [adds some DEFAULT_OPTIONS functionality](https://github.com/lostisland/faraday/releases/tag/v2.10.0) that I introduced a couple days ago (before 2.10.0 was released this morning). It shouldn't affect existing functionality.  I thought I'd help move things along so I can get this feature into my project as intended. Thank you!
* Test are passing locally
> Add support for faraday v2.10.x, tested in CI

- restforce.gemspec
Following user feedback in #901, this updates the gem's dependencies to allow `faraday` versions up to (but not including) v3.0.0.
Previously, due to breaking changes released in minor Faraday versions (see #701 for an example), we have individually vetted new minor versions before declaring Restforce to be compatible.
However, this can slow down apps' Faraday upgrades, and leads to an [odd behaviour][1] where a very old version is installed by default.
We will now automatically allow new minor versions, and a check will only be required for new Faraday major versions. This entails some risk of new minor Faraday versions breaking things - but that's a risk we can choose to take.
[1]: https://github.com/rubygems/rubygems/issues/8002#issuecomment-2328725079
> Allow `faraday` versions up to, but not including, v3.0.0

- README.md
This PR fixes an issue in the documentation where the host parameter for Restforce was incorrectly shown with the https:// protocol. The correct usage is to provide only the domain name, such as login.salesforce.com or test.salesforce.com. This update ensures that future users will avoid connection issues related to improperly formatted URLs.
Error when using incorrect URL 
```
#<Faraday::ConnectionFailed wrapped=#<SocketError: Failed to open TCP connection to https:443 (getaddrinfo: Name or service not known)>>
```
> Fix host parameter documentation in README
